user/urls.py
from django.conf.urls import url,include
from django.contrib.auth import views as auth_views
from . import views
from django.contrib.auth.decorators import login_required
from user.models import Domain

app_name = "user"

urlpatterns = [

    url(r'^@Idealogs$',views.IdealogsHome.as_view(),name="idealogs-home"),
    url(r'^@(?P<id>'+Domain.DOMAIN+')$',views.DomainDetail.as_view(),name="domain"),
    url(r'^@(?P<id>'+Domain.DOMAIN+')/works$',views.DomainWorks.as_view(),name="works"),
    url(r'^@(?P<id>'+Domain.DOMAIN+')/contributors$',views.Contributors.as_view(),name="contributors"),
    url(r'^@(?P<id>'+Domain.DOMAIN+')/contributors/new$',login_required(views.NewContributor.as_view()),name="new-contributor"),
    url(r'^@(?P<id>'+Domain.DOMAIN+')/watch$',login_required(views.Watch.as_view()), name='watch'),
    url(r'^signup$', views.Signup.as_view(), name='signup'),
    url(r'^login$', views.Login.as_view(), name='login'),
    url(r'^@(?P<id>'+Domain.DOMAIN+')/panel$',login_required(views.Panel.as_view()),name='panel'),
    url(r'^panel$',views.PanelRedirectView.as_view(),name='panel-redirect'),
    url(r'^panel/timezone$', login_required(views.Timezone.as_view()), name='timezone'),
    url(r'^panel/hints$', login_required(views.Hints.as_view()), name='hints'),
    url(r'^panel/watching$',login_required(views.Watching.as_view()),name="watching"),
    url(r'^@(?P<id>'+Domain.DOMAIN+')/panel/bio$',login_required(views.Bio.as_view()), name='bio'),
    url(r'^workspace$',login_required(views.Workspace.as_view()), name='workspace'),
    url(r'^workspace/new$',login_required(views.NewWork.as_view()), name='new-work'),
    url(r'^domains$',login_required(views.Domains.as_view()), name='domains'),
    url(r'^domains/new$',login_required(views.NewDomain.as_view()), name='new-domain'),
    url(r'^notifications$',login_required(views.Nots.as_view()),name="nots"),
    url(r'^anon/(?P<ip>.+)$',views.AnonDetail.as_view(),name='anon'), #TODO improve regex for <ip>

    url(r'^panel/password_change/$',views.PasswordChangeView.as_view(),name="password_change"),
    url(r'^panel/password_change/done/$',views.PasswordChangeDoneView.as_view(),name="password_change_done")
]

user/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, PermissionsMixin, AbstractBaseUser
from django.conf import settings
from django.db.models import Q
from django.db import IntegrityError, transaction
from django.core.urlresolvers import reverse
from django.core.validators import RegexValidator
from django.core.exceptions import ValidationError
from django.core.mail import send_mail
from django.contrib.postgres.fields import ArrayField
from django.utils.translation import ugettext_lazy as _
from django.utils.safestring import mark_safe
from django.template.loader import get_template
from timezone_field import TimeZoneField
from datetime import datetime
from django.core.mail import EmailMessage
from urllib.parse import urlparse,unquote
from sortedcontainers import SortedList
from functools import reduce
from . import search
import operator
import hashlib
import re
import pdb

class AnonEditor(models.Model):
    ip = models.CharField(max_length=45,null=True,unique=True)
    is_blocked = models.BooleanField(default=False)

    def __str__(self):
        if self.ip:
            return self.ip
        else:
            return "Anonymous"

    def get_absolute_url(self):
        return reverse("user:anon",kwargs={"ip": self.ip})

class Domain(models.Model):
    DEF = '0'
    TNS = 'T'
    INF = 'I'
    FIN = 'F'
    MAIN = [DEF,TNS,INF,FIN]

    DOMAIN = r'[A-Za-z0-9\.]+'
    DOMAIN_INDEX = r'('+DOMAIN+')x([a-fA-F0-9]+)'

    id = models.CharField(max_length=32,default=DEF,primary_key=True,)
    stops = ArrayField(models.IntegerField(),default=list)
    creators = models.ManyToManyField('Creator')
    watchers = models.ManyToManyField(settings.AUTH_USER_MODEL,related_name="domains_watching")

    next = models.IntegerField(default=0)
    spares = ArrayField(models.IntegerField(),null=True)
    created = models.DateTimeField(auto_now_add=True)
    bio = models.OneToOneField('idealogs.Article',null=True,related_name="bio")

    def __str__(self):
        id = self.id
        for s in self.stops:
            id = id[:s]+'.'+id[s:]
        return id

    def str2(self):
        if self.is_main():
            if self.id == Domain.DEF:
                return mark_safe("@Definite<span style=\'font-size:1.2rem;\'> (<a href=\"#\">?</a>)</span>")
            elif self.id == Domain.TNS:
                return mark_safe("@Transfinite<span style=\'font-size:1.2rem;\'> (<a href=\"#\">?</a>)</span>")
            elif self.id == Domain.INF:
                return mark_safe("@Infinite<span style=\'font-size:1.2rem;\'> (<a href=\"#\">?</a>)</span>")
            elif self.id == Domain.FIN:
                return mark_safe("@Finite<span style=\'font-size:1.2rem;\'> (<a href=\"#\">?</a>)</span>")
        else:
            return "@"+str(self)

    def to_search(self):
        return search.Domain(meta={'id': self.id},
                                id=str(self),
                                created=self.created,)

    def new(input):
        id = input.replace(' ','')
        stops = [stop.start() for stop in re.finditer(' ',input)]
        domain = Domain(id=id,stops=stops)
        domain.save()
        return domain

    def validate(input):
        if not re.match(r'^[A-Z]{1}.*$',input):
            raise ValidationError('first character of pen name must be capitalized')
        elif len(input.replace(' ','')) < 3:
            raise ValidationError('must contain at least three non-whitespace characters')
        elif not re.match(r'^[A-Z\s]+[a-z][A-za-z\s]*$',input):
            raise ValidationError('must contain at least one lower space character')
        elif re.match(Domain.DOMAIN_INDEX,input):
            raise ValidationError('pen name cannot be formatted like an IDea (e.g. ExamplexAF23)')
        elif Domain.objects.filter(id__iexact=input.replace(' ','')).exists():
            raise ValidationError("that name is either taken or reserved")

    def is_main(self):
        return self.id in [Domain.DEF,Domain.TNS,Domain.INF,Domain.FIN]

    def is_tns(self):
        return self.id == Domain.TNS

    def is_def(self):
        return self.id == Domain.DEF

    def is_user(self):
        return hasattr(self,'user')
        # return self.creators.filter(role=Creator.SELF).exists()

    def is_owner(self,user):
        return self.creators.filter(user=user,role__in=[Creator.SELF,Creator.OWNER]).exists()

    def get_owner(self):
        if self.is_user():
            return self.user
        else:
            return self.creators.get(role=Creator.OWNER).user

    def get_objects(self,user):
        return self.article_set.filter(domain=self,creators__user=user,status__gt=0)#Article.PRIVATE

    def get_short_name(self):
        return re.sub('[a-z]','',self.str2())

    def get_absolute_url(self):
        return reverse("user:domain",kwargs={'id':str(self)})

    def get_notification_url(self):
        return self.get_contributors_url()

    def get_contributors_url(self):
        return reverse("user:contributors",kwargs={'id':str(self)})

    def get_works_url(self):
        return reverse("user:works",kwargs={'id':str(self)})

    def get_bio_url(self):
        return reverse("user:bio",kwargs={'id':str(self)})

    def get_new_contributor_url(self):
        return reverse("user:new-contributor",kwargs={'id':str(self)})

    def get_watch_url(self):
        return reverse("user:watch",kwargs={'id':str(self)})

    def get_panel_url(self):
        return reverse("user:panel",kwargs={'id':str(self)})

    def get_timezone_url(self):
        return reverse("user:timezone")

    def get_hints_url(self):
        return reverse("user:hints")

    def translate(x):
        if x == ',':
            return Domain.TNS
        elif x == '.':
            return Domain.INF
        elif x == '?':
            return Domain.FIN
        elif x == ";":
            return Domain.DEF

    def reverse_translate(x):
        if x == Domain.TNS:
            return ','
        elif x == Domain.INF:
            return '.'
        elif x == Domain.FIN:
            return '?'
        elif x == Domain.DEF:
            return ';'

    def translate2(x):
        if x == Domain.TNS:
            return '<strong>writing</strong> (e.g. essay, article, op-ed, book, etc.)'
        elif x == Domain.INF:
            return '<strong>statement</strong>'
        elif x == Domain.FIN:
            return '<strong>question</strong>'
        elif x == Domain.DEF:
            return '<strong>subject</strong> (e.g. World War 2, Climate Change, Ann Arbor, Alexander Hamilton, etc.)'

    def translate3(x):
        if x == Domain.TNS:
            return 'a transfinite (<strong>@Tx...</strong>)'
        elif x == Domain.INF:
            return 'an infinite (<strong>@Ix...</strong>)'
        elif x == Domain.FIN:
            return 'a finite (<strong>@Fx...</strong>)'
        elif x == Domain.DEF:
            return 'a definite (<strong>@0x...</strong>)'

    @transaction.atomic
    def range(self,range=None):
        if range is None:
            if self.spares:
                sl = SortedList(self.spares)
                range = sl.pop(0)
                assert range < self.next
                self.spares = list(iter(sl))
            else:
                range = self.next
                self.next += 1
            self.save()
            return range
        else:
            assert range < self.next
            sl = SortedList(self.spares)
            sl.add(range)
            self.spares = list(iter(sl))
            self.save()

class MyUserManager(BaseUserManager):
    use_in_migrations = True

    """
    A custom user manager to deal with emails as unique identifiers for auth
    instead of usernames. The default that's used is "UserManager"
    """
    def _create_user(self, email, pseudonym, password, **extra_fields):
        """
        Creates and saves a User with the given email and password.
        """
        if not email:
            raise ValueError('The Email must be set')
        if not pseudonym:
            raise ValueError('The Pseudonym must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, pseudonym=pseudonym, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, pseudonym, password=None, **extra_fields):
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, pseudonym, password, **extra_fields)

    def create_superuser(self, email, pseudonym, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
        return self._create_user(email, pseudonym, password, **extra_fields)

class User(AbstractBaseUser, PermissionsMixin):
    domain = models.OneToOneField(Domain,on_delete=models.CASCADE,null=True)
    email = models.EmailField(unique=True,)
    timezone = TimeZoneField(default='US/Eastern')
    hints = models.BooleanField(default=True)
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    USERNAME_FIELD = 'email'
    objects = MyUserManager()
    REQUIRED_FIELDS = ['pseudonym']

    def __str__(self):
        return "@"+str(self.domain)

    def initialize(self,pseudonym):
        self.domain = Domain.new(pseudonym)

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load tz %}
{% load notifications_tags %}
{% notifications_unread as unread_count %}
{% localtime on %}
<html>
  <head>
    <meta charset="utf-8">
    <meta name="generator" content="pandoc">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
    {% block styles %}
      <link rel="stylesheet" href="{% static 'tufte.css' %}?2">
      <link rel="stylesheet" href="{% static 'latex.css' %}?2">
      <link rel="stylesheet" href="{% static 'pandoc-solarized.css' %}?2">
      <link rel="stylesheet" href="{% static 'pandoc.css' %}?2">
      <link rel="stylesheet" href="{% static 'tufte-extra.css' %}?2">
      <link rel="stylesheet" href="{% static 'et_book.css' %}?2">
      <link rel="stylesheet" href="{% static 'master.css' %}?2">
    {% endblock %}
    <script src="{% static 'js/jquery-3.1.1.min.js' %}?2"></script>
    <script src="{% static 'js/jquery_cookie.js' %}?2"></script>
    <script src="{% static 'js/autosize.min.js' %}?2"></script>
    <!-- <script src="{% static 'notifications/notify.js' %}?2" type="text/javascript"></script>
    {% register_notify_callbacks callbacks='fill_notification_list,fill_notification_badge' %} -->

    {% block mathjax %}
    {% endblock %}

    {% block head %}
      <title>{% if noheader %}{% elif header %}{{header}} - {% elif title %}{{title}} - {% elif object %}{{object}} - {% elif domain %}@{{domain}} - {% endif %}Idealogs</title>
    {% endblock %}

    {% if not DEBUG %}
      <!-- Global site tag (gtag.js) - Google Analytics -->
      <script async src="https://www.googletagmanager.com/gtag/js?id=UA-146150405-1"></script>
      <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-146150405-1');
      </script>
    {% endif %}

  </head>
  <body>
    <main>
      {% block content %}
      {% endblock %}
    </main>
    <div id='footer'>
      {% include 'footer.html' %}
    </div>
    {% block script %}
    {% endblock %}

    <!-- hack: nav-grid is placed after the main body so that the foo nav links aren't covered up. Sticky footers are the worst, also death to css -->
    <div class="nav-grid">
      <div class="topnav" style="font-weight:bold;">
        <div class="topnav-left">
          <div>&laquo;<a href="{% url 'index' %}">Idealogs</a>&raquo;</div>
          <div>|</div>
          <div class="nav-fixin"><a href="{% url 'meta' %}">Meta</a></div>
          <div class="nav-fixin">|</div>
          <div><a href="/@Enderx0">Welcome</a></div>
        </div>
        <div class="topnav-right">
          {% if request.user.is_authenticated %}
            <div><a href="{{request.user.domain.get_absolute_url}}">{{request.user.domain.get_short_name}}</a></div>
            <div>|</div>
            <div class="nav-fixin"><a href="{% url 'user:workspace' %}">Workspace</a></div>
            <div class="nav-fixin">|</div>
            <div class="nav-fixin"><a href="{% url 'user:domains' %}">Domains</a></div>
            <div class="nav-fixin">|</div>
            <div><a href="{% url 'user:nots' %}">Nots {% if unread_count %}({% live_notify_badge %}){% endif %}</a></div>
            <div>|</div>
            <div><a href="{% url 'logout' %}?next={{ request.get_full_path|urlencode }}">Logout</a></div>
          {% else %}
            <div><a href="{% url 'user:signup' %}">Sign Up</a></div>
            <div>|</div>
            <div><a href="{% url 'user:login' %}?next={{ request.get_full_path|urlencode }}">Login</a></div>
          {% endif %}
        </div>
      </div>

      {% block foonav %}
        <div class="foonav">
          <div class="foonav-left">
            {% block leftfoonav %}
            {% endblock %}
          </div>
          <div class="foonav-right">
            {% block rightfoonav %}
              {% include 'search_bar.html' %}
            {% endblock %}
          </div>
        </div>
      {% endblock %}
    </div>

  </body>
</html>
{% endlocaltime %}

templates/contact.html
{% extends "form.html" %}
{% load staticfiles %}

{% block head %}
  <title>Contact - Idealogs</title>
{% endblock %}

{% block content %}
  <article>
    <h1>{{title}}</h1>
    <p class="subtitle">{{subtitle|safe}}</p>
    <form method="POST" class="post-form">
      {% csrf_token %}
      <div class="foo">
        <p>Need to get in touch? Include your message and an email where I can reach you below.</p>
        {{form.errors}}
        {% for field in form %}
          {% if field.label == "Subject" %}
            <div class="commit-message-textarea">
              <textarea name="subject" placeholder="Subject" style="resize:none;margin-bottom:-.5rem;height:0rem;" id="id_subject" required rows="1">{% if field.value %}{{field.value}}{% endif %}</textarea>
            </div>
          {% elif field.label == "Document" %}
            <div class="expandingArea" style="border-top:0;">
              <textarea name="document" placeholder="Message" style="resize:none;margin-bottom:-.5rem;min-height:42.5vh;" id="id_document" required>{% if field.value %}{{field.value}}{% endif %}</textarea>
            </div>
          {% elif field.label == "Email" %}
            <div class="commit-message-textarea" style='border-top:0;'>
              <textarea name="email" placeholder="Email" style="resize:none;margin-bottom:-.5rem;height:0rem;" id="id_email" required rows="1">{% if field.value %}{{field.value}}{% endif %}</textarea>
            </div>
          {% endif %}
        {% endfor %}
      </div>
      <button type="submit" name="button" style='margin-top:1rem;'>Submit</button>
    </form>
  </article>
{% endblock %}

{% block script %}
  <script src="{% static 'idealogs/update.js' %}?2"></script>
  <script>autosize($('#id_email'));</script>
  <script>autosize($('#id_subject'));</script>
{% endblock %}

templates/footer.html
{% block footer %}
  <div class='footer-text'>{{license|safe}} By using this site, you agree to the <a href="{% url 'tos' %}">Terms of Use</a> and <a href="{% url 'privacy' %}">Privacy Policy</a>.  Idealogs&reg; is a registered trademark of the Idealogical Foundation, Inc., a non-profit organization.</div>
{% endblock %}
<div class='footer-links'>
  <div><a href="{% url 'about' %}">About</a></div><div class='footer-link'>|</div>
  <div><a href="{% url 'contact' %}">Contact</a></div><div class='footer-link'>|</div>
  <div><a href="/@0x1">Docs</a></div><div class='footer-link'>|</div>
  <div><a href="{% url 'developers' %}">Developers</a></div><div class='footer-link'>|</div>
  <div><a href="{% url 'donate' %}">Donate</a></div>
</div>

templates/form.html
{% extends "base.html" %}
{% load staticfiles %}
{% load notifications_tags %}
{% notifications_unread as unread_count %}
{% load idealogs_extras %}

{% block leftfoonav %}
  {% if idealogs %}
    {% include 'idealogs/util/leftfoo.html' %}
  {% endif %}
{% endblock %}

{% block rightfoonav %}
  {% if idealogs %}
    {% include 'idealogs/util/rightfoo.html' %}
  {% endif %}
  {{block.super}}
{% endblock %}

{% block content %}
  <article>
    <h1>{{title|wbr|safe}}</h1>
    <p class="subtitle">{{subtitle|safe}}</p>
    <div class="foo">
      <form method="POST" class="post-form">
        {% csrf_token %}
        <!-- <section> -->
          {{form.as_p}}
        <!-- </section> -->
        {% block form-extra %}{% endblock %}
        <button type="submit" {% block onclick %}{% endblock %}>Submit</button>
      </form>
    </div>
  </article>
{% endblock %}

templates/index.html
{% extends "list.html" %}
{% load staticfiles %}

{% block script %}
  <script src="{% static 'idealogs/index.js' %}?2"></script>
{% endblock %}

templates/list.html
{% extends "base.html" %}
{% load staticfiles %}
{% load idealogs_extras %}

{% block leftfoonav %}
  {% if idealogs %}
    {% include 'idealogs/util/leftfoo.html' %}
  {% endif %}
{% endblock %}

{% block rightfoonav %}
  {% if idealogs %}
    {% include 'idealogs/util/rightfoo.html' %}
  {% endif %}
  {{block.super}}
{% endblock %}

{% block content %}
  <article>
    <h1>{{title|wbr|safe}}</h1>
    {% if subtitle %}
      <p class="subtitle">{{subtitle|safe}}</p>
    {% endif %}
    {% if subaction_href %}
      <p class="byline">Bio: <a href="{{subaction_href}}">{{subaction_title}}</a></p>
    {% endif %}
    {% include 'search_list.html' %}
  </article>
{% endblock %}

templates/new.html
{% extends "base.html" %}
{% load staticfiles %}

{% block head %}
  <title>New - Idealogs</title>
{% endblock %}

{% block content %}
  <article>
    <h1>Idealogs</h1>
    <p class="subtitle">{{subtitle|safe}}</p>
    <form method="POST" class="post-form" id="update-form">
      {% csrf_token %}
      <div class="foo">
        <div style='display:none;'>
          <input name="identifier" type="text" required id="identifier" value="{{query}}"></input>
        </div>
        <div class="update-search">
          <input name="identifier2" {% if not query %}autofocus="autofocus"{% endif %} type="text" placeholder="Entry" required id="id_search" value="{{query}}"></input>
        </div>
        <div id="query" class="query-disabled">
          <div class="query-item-category">
          </div>
          <div class="query-item-follow">
            <div class="query-item-aquo query-laquo">
            </div>
            <div class="query-item-aquo query-raquo">
            </div>
          </div>
          <div class="query-item"></div>
          <div class="query-item-description"></div>
        </div>
        {% if hints %}
          <div class="feed-container">
            {% for object in hints %}
              {% include 'feed/hint.html' %}
            {% endfor %}
          </div>
        {% endif %}
      </div>
    </form>
  </article>
{% endblock %}

{% block script %}
  <script src="{% static 'idealogs/query.js' %}?2"></script>
{% endblock %}

templates/pandoc.html
<!DOCTYPE html>
<html$if(lang)$ lang="$lang$"$endif$$if(dir)$ dir="$dir$"$endif$>
<head>
  <meta charset="utf-8">
  <meta name="generator" content="pandoc">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
$for(author-meta)$
  <meta name="author" content="$author-meta$">
$endfor$
$if(date-meta)$
  <meta name="dcterms.date" content="$date-meta$">
$endif$
$if(keywords)$
  <meta name="keywords" content="$for(keywords)$$keywords$$sep$, $endfor$">
$endif$
  <title>$if(title-prefix)$$title-prefix$ – $endif$$pagetitle$</title>
  <style type="text/css">code{white-space: pre;}</style>
$if(quotes)$
  <style type="text/css">q { quotes: "“" "”" "‘" "’"; }</style>
$endif$
$if(highlighting-css)$
  <style type="text/css">
$highlighting-css$
  </style>
$endif$
$for(css)$
  <link rel="stylesheet" href="$css$">
$endfor$
$if(math)$
  $math$
$endif$
  <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv-printshiv.min.js"></script>
  <![endif]-->
$for(header-includes)$
  $header-includes$
$endfor$
</head>
<body>
$for(include-before)$
$include-before$
$endfor$
<article>
$if(toc)$
<nav id="$idprefix$TOC">
<div class="toc">
<p><span id="context-heading"></span></p>
$toc$
</div>
</nav>
$endif$
$body$
</article>
$for(include-after)$
$include-after$
$endfor$
</body>
</html>

templates/search_bar.html
<div class="navsearch">
  <form action="{% url 'search' %}" method="get" accept-charset="utf-8">
    <input name="q" type="text" placeholder="Search">
    <input type="submit" style="display: none" />
  </form>
</div>

templates/search_list.html
<div class="foo">
  <div class="update-search">
    <form action="{{action}}" method="get">
      <input name="q" placeholder="{{placeholder}}" {% if autofocus and not request.GET.q %}autofocus="autofocus"{% endif %} id="id_search" value="{{request.GET.q}}"></input>
      <input type="submit" style="display:none;"/>
    </form>
  </div>
  {% if feed or hints %}
    <div class="feed-container">
      {% if title == 'History' %}
        <form method="post" class='changes-form' onsubmit="return mySubmit();">
          {% csrf_token %}
      {% endif %}
      {% for object in feed %}
        {% include template %}
      {% endfor %}
      {% if title == 'History' %}
        </form>
      {% endif %}
      {% for object in hints %}
        {% include 'feed/hint.html' %}
      {% endfor %}
    </div>
    {% if is_paginated %}
      <div class="pagination" style='font:serif;'>
        {% if feed.has_previous %}
          <a href="{{request.path}}?q={{request.GET.q}}&page={{ feed.previous_page_number }}">&laquo;</a>
        {% else %}
          &laquo;
        {% endif %}
        {% if feed.has_next %}
          <a href="{{request.path}}?q={{request.GET.q}}&page={{ feed.next_page_number }}">&raquo;</a>
        {% else %}
          &raquo;
        {% endif %}
      </div>
    {% endif %}
  {% else %}
    <p>No results.</p>
  {% endif %}
</div>